name: chabud
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-lock=1.4.0
  - h5netcdf=1.1.0
  - jupyterlab=3.6.3
  - lightning=2.0.2
  - python=3.11.3
  - python-graphviz=0.20.1
  - torchdata=0.6.0
  - xarray-datatree=0.0.12
platforms:
  - linux-64
