# This workflow will install Python dependencies and run tests on a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-22.04]

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      # Install Micromamba with conda-forge dependencies
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@1887e3afc05fd11eb40c9542c2939ac04234546e # v1.2.1
        with:
          environment-name: chabud
          environment-file: conda-lock.yml

      # Show installed packages
      - name: List installed packages
        run: micromamba list

      # Run the unit tests
      - name: Test with pytest
        run: |
            micromamba install python=${{ matrix.python-version }} pytest
            python -m pytest --verbose chabud/tests/
        shell: micromamba-shell {0}
