# This workflow will install Python dependencies and run tests on a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-22.04]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      # Install Micromamba with conda-forge dependencies
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@e2b397b12d0a38069451664382b769c9456e3d6d # v15
        with:
          environment-name: chabud
          environment-file: conda-lock.yml
          extra-specs: |
            python=${{ matrix.python-version }}
            pytest

      # Show installed packages
      - name: List installed packages
        run: micromamba list

      # Run the unit tests
      - name: Test with pytest
        run: python -m pytest --verbose chabud/tests/
